---
language: python
install: which tox >/dev/null || if [ -z ${VIRTUAL_ENV+x} ]; then python -m pip install --user tox tox-pyenv ; else python -m pip install tox tox-pyenv twine; fi
script:
- tox
stages:
  - test
  - deploy
jobs:
  include:
    - python: '2.7'
      env: TOXENV=py27
    - python: '3.4'
      env: TOXENV=py34
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37 PYTHON='3.7'
      # begin: workaround to enable support for py37: https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      sudo: required
      # end
    - stage: deploy
      deploy:
        provider: pypi
        user: Dev-Oss
        password:
          secure: AeTh3w8QeXQ6StzHlIbQcYZnr1qRjkQ4lBV0zup1t43dXxoRaXbQ7x2ZwcYpbM2h/lWeWssU2G6iY5ZW4a2t0+4go3PMPLSo2AC/sNJyVeuxvefkXTlWsL2YkTitpB1hhEzBVLMczNgf2OpLrmJIS/3hh1p3smiyj2xt1Jf7TaQ3bGneVFmlFrbOQTz5caoqjTRkhDWEa38pnSpbNIlgHIwhuDpVfUZn+Gh/UXmWdgiE1srpI1YLEMjpiFTe39Y36XvaJ/xszd/a929YgOalTZws+8iCzvI+/vSKdf1G+Phc4iVRbqwHAc4lfzbl42Yy81IMBrCMia/uum/lgkxZtcMJzyBwDXA0Rxtp1Ayh27bwI02tdJ3VQ8X8zvDJjATQhL2dRA5jqjNTco3SugM5rGcOvuLyjgROI9hQV0PSOXydqA/5kfLir5Y0cEpn5xW/RRVW5xgG9Pl6SzpS5vyd4/FB02wnp4pSxJM3v8WOUvMgKK4XjmMKKE8+IrY+avLLrhg3y3ziHdtjrnsVjo+fX+pdxymy85cNDVVH+AfBhG+Hnf2svxA4HnKzN9QaTGLB7EjU8TYCa1eJ8djSbEF9MStw2+b3cUG65jvWjDt/sPwzmcsrAob4rcy5pIBQbbtAa48lqighjjpM8EkDepLJaduDYUIbf3K+dKNjsKBXAo4=
        on:
          tags: true
